### ISSUE TITLE
no ps0.pyc in your .gitignore?

### ISSUE THREAD

**Issue by JoshOrndorff** [lindseyyu/ps0#1]
If you never got a ps0.pyc, then no need to ignore it, but I'm guessing that file cropped up at some point.

**Comment by lindseyyu** [comment]
You were right! It was in my folder unknowingly, so I added to the ignore file. 
![screen shot 2016-04-09 at 3 58 31 pm](https://cloud.githubusercontent.com/assets/17552526/14406133/62f870dc-fe6c-11e5-9629-cea267497f17.png)
