### ISSUE TITLE
sum_less_ints sums too many ints

### ISSUE THREAD

**Issue by JoshOrndorff** [lindseyyu/ps0#2]
Desired behavior:     sum_less_ints(5) -> 1 + 2 + 3 + 4
Observed behavior: sum_less_ints(5) ->  1 + 2 + 3 + 4 + 5

**Comment by lindseyyu** [comment]
![screen shot 2016-04-09 at 3 58 15 pm](https://cloud.githubusercontent.com/assets/17552526/14406082/31a1ecc0-fe6c-11e5-9ea0-faf1fefd46cb.png)

Adjusted loop to avoid the actual int from being added to the list. (less int list no longer includes 5)

**Comment by JoshOrndorff** [comment]
Looks good.
