### ISSUE TITLE
mod operator backward in is_factor function

### ISSUE THREAD

**Issue by JoshOrndorff** [lindseyyu/ps0#3]
I think you meant number1 % number 2 on line 85, not the other way around.

**Comment by lindseyyu** [comment]
![screen shot 2016-04-09 at 3 58 22 pm](https://cloud.githubusercontent.com/assets/17552526/14406073/1ba3d410-fe6c-11e5-9e14-88d40fd5506c.png)

Flipped them around and adjusted my ps0-runner accordingly.

**Comment by jorndorff** [comment]
Yep, it looks right now.

Out of curiosity, why are you casting to int there?
