### ISSUE TITLE
is_even returning string instead of bool

### ISSUE THREAD

**Issue by JoshOrndorff** [lindseyyu/ps0#4]
It returns the strings "Odd" or "Even" instead of the bools False or True.

**Comment by lindseyyu** [comment]
![screen shot 2016-04-09 at 3 58 00 pm](https://cloud.githubusercontent.com/assets/17552526/14406056/00741c0e-fe6c-11e5-8d01-404f24ae69b7.png)

Fixed function, so it would return bools False of True instead of strings

**Comment by JoshOrndorff** [comment]
Looks right. You don't have to go to all the effort to include the screenshot. Users can see the update in your latest commit. Feel free to close issues after you fix them too. I'll close this one.
